/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.5
 * Generated at: 2026-02-20 01:26:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.*;

public final class findcourse_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/searchresults.jsp", Long.valueOf(1771425940240L));
    _jspx_dependants.put("/modal/error.jsp", Long.valueOf(1771411381495L));
    _jspx_dependants.put("/courseenrolment.jsp", Long.valueOf(1771550273771L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <title>UniX - Enrolment</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/css/style.css\">\r\n");
      out.write("    <style>\r\n");
      out.write("        th,\r\n");
      out.write("        td {\r\n");
      out.write("            border: 1px solid #ccc;\r\n");
      out.write("            padding: 5px 8px;\r\n");
      out.write("            text-align: left;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    <header>\r\n");
      out.write("        <img src=\"/images/UniXLogo.jpg\" height=\"32px\" />\r\n");
      out.write("        <h1>Course Enrolment</h1>\r\n");
      out.write("        <div class=\"icon-container\" style=\"gap:20px\">\r\n");
      out.write("            <div class=\"icon-container\">\r\n");
      out.write("                <img src=\"/images/User.png\" height=\"24px\" />\r\n");
      out.write("                <p>\r\n");
      out.write("                    ");
      out.print(session.getAttribute("username") );
      out.write("\r\n");
      out.write("                </p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <button class=\"icon-container\" onclick=\"location.href='LogoutServlet'\">\r\n");
      out.write("                <img src=\"/images/LogOut.png\" height=\"24px\" />\r\n");
      out.write("                Log Out</button>\r\n");
      out.write("        </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </header>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"container\" style=\"margin-top: 22px;\">\r\n");
      out.write("        <div style=\"width: 80%; max-width: 600px;text-align: left;\">\r\n");
      out.write("            <button class=\"icon-container\" style=\"padding: 2px 2px;margin-bottom: 10px;border-radius: 100px; position: relative;\r\n");
      out.write("    left: -4px;\" onclick=\"location.href='SemesterSelectionServlet'\">\r\n");
      out.write("                <img src=\"/images/Arrow left.png\" height=\"24px\" /></button>\r\n");
      out.write("            <h2>Find Course</h2>\r\n");
      out.write("            <hr>\r\n");
      out.write("            <p style=\"margin-bottom: 10px;\">Search for courses offered in Semester 1 - 2026 by Course Code</p>\r\n");
      out.write("            <form action=\"FindCourseServlet\" method=\"post\">\r\n");
      out.write("                <label for=\"coursecode\">Course Code</label><br>\r\n");
      out.write("                <input type=\"text\" id=\"coursecode\" name=\"coursecode\" placeholder=\"Enter Course Code (e.g. SENG2050)\"\r\n");
      out.write("                    style=\"width: 50%; max-width: 250px\">\r\n");
      out.write("                <button type=\"submit\" style=\"padding: 5px 15px;font-size: 16px;margin-left: 20px;\">Search</button>\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div style=\"width: 80%; max-width: 600px;text-align: left;\">\r\n");
      out.write("            <h2>Select a Course</h2>\r\n");
      out.write("            <hr>\r\n");
      out.write("            <p style=\"margin-bottom: 10px;\">Select a course to enrol in semester 1 - 2026</p>\r\n");
      out.write("            ");
      out.write("\r\n");
      out.write("    <!DOCTYPE html>\r\n");
      out.write("    <html>\r\n");
      out.write("    <style>\r\n");
      out.write("        .resultbox {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            padding: 10px;\r\n");
      out.write("            background-color: white;\r\n");
      out.write("            color: black;\r\n");
      out.write("            border: #c5c5c5 1px solid;\r\n");
      out.write("            border-radius: 3px;\r\n");
      out.write("            margin: 10px 0;\r\n");
      out.write("            text-align: left;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .resultbox:hover {\r\n");
      out.write("            background-color: #E6ECF7;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("    ");
 // List (results) from Controller 
    List courses=(List) request.getAttribute("courses"); // objects 
    if(courses!=null && !courses.isEmpty()) { for (Object obj : courses) { Map course=(Map) obj; 
      out.write("\r\n");
      out.write("        <form action=\"CourseEnrolmentServlet\" method=\"get\">\r\n");
      out.write("            <input type=\"hidden\" name=\"coursecode\" value=\"SENG2050\" /><!--hardcoded-->\r\n");
      out.write("            <button class=\"resultbox\" type=\"submit\" onclick=\"toggleSidebar()\">\r\n");
      out.write("                <div class=\"icon-container\" style=\"margin-top: 5px;\">\r\n");
      out.write("                    <p style=\"margin-right: 20px;color:#003AA6\">\r\n");
      out.write("                        ");
      out.print( course.get("code") );
      out.write("\r\n");
      out.write("                    </p>\r\n");
      out.write("                    ");
 if((Boolean)course.get("open")) { 
      out.write("\r\n");
      out.write("                        <span\r\n");
      out.write("                            style=\"display: inline-block; width: 10px; height: 10px; background-color: #00AF0F; border-radius: 50%;\"></span>\r\n");
      out.write("                        <p>Open</p>\r\n");
      out.write("                        ");
 } else {
      out.write("\r\n");
      out.write("                            <span\r\n");
      out.write("                                style=\"display: inline-block; width: 10px; height: 10px; background-color: #c5c5c5; border-radius: 50%;\"></span>\r\n");
      out.write("                            <p>Closed</p>\r\n");
      out.write("                            ");
 } 
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("                <p style=\"font-weight: bold;\">\r\n");
      out.write("                    ");
      out.print( course.get("name") );
      out.write("\r\n");
      out.write("                </p>\r\n");
      out.write("            </button>\r\n");
      out.write("        </form>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("            ");
} else {
      out.write("\r\n");
      out.write("                <p style=\"margin-top: 40px; font-weight: bold;\">No courses found</p>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("    </html>");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div style=\"width: 80%; max-width: 600px;text-align: left;\">\r\n");
      out.write("            <h2>Current Enrolments</h2>\r\n");
      out.write("            <table style=\"width: 100%; border: 1px solid #c5c5c5;border-collapse: collapse; margin-top: 20px;\">\r\n");
      out.write("                <thead style=\"background-color: #c5c5c5;\">\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th>Course</th>\r\n");
      out.write("                        <th>Units</th>\r\n");
      out.write("                        <th>Status</th>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                </thead>\r\n");
      out.write("                <tbody>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>MATH2021 - Discrete Mathematics</td>\r\n");
      out.write("                        <td>10</td>\r\n");
      out.write("                        <td>Enrolled</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>COMP2020 - Data Structure</td>\r\n");
      out.write("                        <td>10</td>\r\n");
      out.write("                        <td>Enrolled</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                </tbody>\r\n");
      out.write("            </table>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    ");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<style>\r\n");
      out.write("    .sidebar {\r\n");
      out.write("        height: 100%;\r\n");
      out.write("        width: 30%;\r\n");
      out.write("        min-width: 200px;\r\n");
      out.write("        max-width: 400px;\r\n");
      out.write("        position: fixed;\r\n");
      out.write("        top: 0px;\r\n");
      out.write("        right: -250px;\r\n");
      out.write("        border-left: 1px solid #c5c5c5;\r\n");
      out.write("        border-top: 1px solid #c5c5c5;\r\n");
      out.write("        padding-top: 20px;\r\n");
      out.write("        transition: 0.3s;\r\n");
      out.write("        margin-top: 74px;\r\n");
      out.write("        background-color: white;\r\n");
      out.write("        box-shadow: -8px 0 20px rgba(0, 0, 0, 0.10);\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
 String targetcourse=(String) request.getAttribute("targetcourse"); if (targetcourse!=null && !targetcourse.isEmpty())
    { 
      out.write("\r\n");
      out.write("    <div class=\"sidebar\" id=\"Sidebar\" style=\"padding: 20px\">\r\n");
      out.write("        <p style=\"margin-right: 20px;color:#003AA6\">\r\n");
      out.write("            ");
      out.print( targetcourse );
      out.write("\r\n");
      out.write("        </p>\r\n");
      out.write("\r\n");
      out.write("        <p style=\"font-weight: bold;\">\r\n");
      out.write("            Web Engineering\r\n");
      out.write("        </p>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <p style=\"margin-bottom: 20px;\"><span\r\n");
      out.write("                style=\"display: inline-block; width: 10px; height: 10px; background-color: #00AF0F; border-radius: 50%;\"></span>Open\r\n");
      out.write("        </p>\r\n");
      out.write("\r\n");
      out.write("        <p>Location: Callaghan</p>\r\n");
      out.write("        <p>Units: 10</p>\r\n");
      out.write("        <p>Student Level: Undergraduate</p>\r\n");
      out.write("        <p style=\"margin-bottom: 10px;\">Course Level: 2000-level</p>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <p style=\"margin-bottom: 10px;\">Prerequisite (must be completed)<br>SENG1050</p>\r\n");
      out.write("        <p>Assumed Knowledge<br>COMP1140 and SENG1110, or INFT1004 (or equivalent) </p>\r\n");
      out.write("        <div class=\"button-container\">\r\n");
      out.write("            <form action=\"CourseEnrolmentServlet\" method=\"post\">\r\n");
      out.write("                <input type=\"hidden\" name=\"course\" value=\"SENG2050\"/>\r\n");
      out.write("                <button type=\"submit\" style=\"padding: 5px 15px;font-size: 16px;margin-top: 40px;\">Enrol</button>\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    ");
 } 
      out.write("\r\n");
      out.write("        ");
 Boolean openSidebar=(Boolean) request.getAttribute("openSidebar"); if(openSidebar !=null && openSidebar) { 
      out.write("\r\n");
      out.write("            <script>\r\n");
      out.write("                function toggleSidebar() {\r\n");
      out.write("                    var sidebar = document.getElementById(\"Sidebar\");\r\n");
      out.write("                    if (sidebar.style.right === \"0px\") {\r\n");
      out.write("                        sidebar.style.right = \"-250px\"; // ë«ê¸°\r\n");
      out.write("                    } else {\r\n");
      out.write("                        sidebar.style.right = \"0px\";    // ì´ê¸°\r\n");
      out.write("                    }\r\n");
      out.write("                }\r\n");
      out.write("                window.onload = function () {\r\n");
      out.write("                    setTimeout(toggleSidebar, 10);\r\n");
      out.write("                };\r\n");
      out.write("\r\n");
      out.write("            </script>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    ");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<!-- show modal if login failed -->\r\n");
 Boolean Error=(Boolean) request.getAttribute("Error"); 
      out.write("\r\n");
      out.write("    <dialog id=\"error\">\r\n");
      out.write("        <div style=\"display: flex;align-items: center;margin-bottom: 20px;\">\r\n");
      out.write("            <img src=\"../images/Alert circle.png\" height=\"20px\" />\r\n");
      out.write("            <h4 style=\"margin-left: 10px;\">\r\n");
      out.write("                ");
      out.print( request.getAttribute("errorTitle"));
      out.write("\r\n");
      out.write("            </h4>\r\n");
      out.write("        </div>\r\n");
      out.write("        <p style=\"margin-bottom: 20px\">\r\n");
      out.write("            ");
      out.print( request.getAttribute("errorContent"));
      out.write("\r\n");
      out.write("        </p>\r\n");
      out.write("        <div class=\"button-container\">\r\n");
      out.write("            <button commandfor=\"error\" command=\"close\">Close</button>\r\n");
      out.write("        </div>\r\n");
      out.write("    </dialog>\r\n");
      out.write("\r\n");
      out.write("    ");
 if (Error !=null && Error) {
      out.write("\r\n");
      out.write("        <script>\r\n");
      out.write("            const dialog = document.getElementById(\"error\");\r\n");
      out.write("            dialog.showModal();\r\n");
      out.write("        </script>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
