/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.5
 * Generated at: 2026-03-15 04:06:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.*;
import seng2050.Semester;
import seng2050.Student;
import seng2050.Course;
import seng2050.Course;

public final class findcourse_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/modal/warning.jsp", Long.valueOf(1773542946176L));
    _jspx_dependants.put("/modal/error.jsp", Long.valueOf(1773458812671L));
    _jspx_dependants.put("/modal/confirm.jsp", Long.valueOf(1773538940465L));
    _jspx_dependants.put("/courseenrolment.jsp", Long.valueOf(1773487281077L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("seng2050.Course");
    _jspx_imports_classes.add("seng2050.Student");
    _jspx_imports_classes.add("seng2050.Semester");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("        \r\n");
      out.write("            \r\n");
      out.write("\r\n");
      out.write("                <!DOCTYPE html>\r\n");
      out.write("                <html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("                <head>\r\n");
      out.write("                    <title>UniX - Enrolment</title>\r\n");
      out.write("                    <link rel=\"stylesheet\" href=\"/css/style.css\">\r\n");
      out.write("                    <style>\r\n");
      out.write("                        th,\r\n");
      out.write("                        td {\r\n");
      out.write("                            border: 1px solid #ccc;\r\n");
      out.write("                            padding: 5px 8px;\r\n");
      out.write("                            text-align: left;\r\n");
      out.write("                        }\r\n");
      out.write("\r\n");
      out.write("                        .resultbox {\r\n");
      out.write("                            width: 100%;\r\n");
      out.write("                            padding: 10px;\r\n");
      out.write("                            background-color: white;\r\n");
      out.write("                            color: black;\r\n");
      out.write("                            border: #c5c5c5 1px solid;\r\n");
      out.write("                            border-radius: 3px;\r\n");
      out.write("                            margin: 10px 0;\r\n");
      out.write("                            text-align: left;\r\n");
      out.write("                        }\r\n");
      out.write("\r\n");
      out.write("                        .resultbox:hover {\r\n");
      out.write("                            background-color: #D9E7FF;\r\n");
      out.write("                        }\r\n");
      out.write("                    </style>\r\n");
      out.write("                </head>\r\n");
      out.write("\r\n");
      out.write("                <body>\r\n");
      out.write("                    <header>\r\n");
      out.write("                        <img src=\"/images/UniXLogo.jpg\" height=\"32px\" />\r\n");
      out.write("                        <h1>Course Enrolment</h1>\r\n");
      out.write("                        <div class=\"icon-container\" style=\"gap:20px\">\r\n");
      out.write("                            <div class=\"icon-container\">\r\n");
      out.write("                                <img src=\"/images/User.png\" height=\"24px\" />\r\n");
      out.write("                                ");
 Student student=(Student) session.getAttribute("student"); 
      out.write("\r\n");
      out.write("                                    <p>\r\n");
      out.write("                                        ");
      out.print(student.getGivenNames() );
      out.write("\r\n");
      out.write("                                            ");
      out.print(student.getLastName() );
      out.write("\r\n");
      out.write("                                    </p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <button class=\"icon-container\" onclick=\"location.href='LogoutServlet'\">\r\n");
      out.write("                                <img src=\"/images/LogOut.png\" height=\"24px\" />\r\n");
      out.write("                                Log Out</button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </header>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"container\" style=\"margin-top: 22px;\">\r\n");
      out.write("                        <div style=\"width: 80%; max-width: 600px;text-align: left;\">\r\n");
      out.write("                            <button class=\"icon-container\" style=\"padding: 2px 2px;margin-bottom: 10px;border-radius: 100px; position: relative;\r\n");
      out.write("    left: -4px;\" onclick=\"location.href='SemesterSelectionServlet'\">\r\n");
      out.write("                                <img src=\"/images/Arrow left.png\" height=\"24px\" /></button>\r\n");
      out.write("                            <h2>Find Course</h2>\r\n");
      out.write("                            <hr>\r\n");
      out.write("                            ");
 Semester semester=(Semester) session.getAttribute("semester"); 
      out.write("\r\n");
      out.write("                                <p style=\"margin-bottom: 30px;\">Search for courses offered in Semester\r\n");
      out.write("                                    ");
      out.print(semester.getSemester() );
      out.write(' ');
      out.write('-');
      out.write(' ');
      out.print(semester.getYear());
      out.write(" by Course Code</p>\r\n");
      out.write("                                <form action=\"FindCourseServlet\" method=\"get\">\r\n");
      out.write("                                    <label for=\"search\">Course Code</label><br>\r\n");
      out.write("                                    ");
 String searchString = (String) request.getAttribute("search") != null ? (String) request.getAttribute("search") : ""; 
      out.write("\r\n");
      out.write("                                        <input type=\"text\" id=\"search\" name=\"search\"\r\n");
      out.write("                                        placeholder=\"Enter Course Code (e.g. SENG2050)\"\r\n");
      out.write("                                        value=\"");
      out.print( searchString );
      out.write("\"\r\n");
      out.write("                                        style=\"width: 50%; max-width: 250px; height: 30px; margin-top: 8px\"\r\n");
      out.write("                                        maxlength=\"10\">\r\n");
      out.write("                                    <button type=\"submit\"\r\n");
      out.write("                                        style=\"padding: 6px 20px;font-size: 16px;margin-left: 20px;\">Search</button>\r\n");
      out.write("                                </form>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"container\">\r\n");
      out.write("                        <div style=\"width: 80%; max-width: 600px;text-align: left;\">\r\n");
      out.write("                            <h2>Select a Course</h2>\r\n");
      out.write("                            <hr>\r\n");
      out.write("                            <p style=\"margin-bottom: 10px;\">Select a course to enrol in Semester\r\n");
      out.write("                                ");
      out.print(semester.getSemester() );
      out.write(' ');
      out.write('-');
      out.write(' ');
      out.print(semester.getYear());
      out.write("\r\n");
      out.write("                            </p>\r\n");
      out.write("                            ");
 Boolean showSearchResult = (Boolean) session.getAttribute("showSearchResult");
                                if(showSearchResult!=null && showSearchResult) {
                                    List<Course> courses=(List<Course>) session.getAttribute("searchresults");
                                    if(courses!=null && !courses.isEmpty()) {
                                    for (Course course : courses) { 
      out.write("\r\n");
      out.write("                                    <form action=\"CourseEnrolmentServlet\" method=\"get\">\r\n");
      out.write("                                        <input type=\"hidden\" name=\"coursecode\" value=\"");
      out.print(course.getCourseID() );
      out.write("\" />\r\n");
      out.write("                                        <button class=\"resultbox\" type=\"submit\">\r\n");
      out.write("                                            <span style=\"margin-bottom: 5px;color:#003AA6; display: inline-block;\">\r\n");
      out.write("                                                ");
      out.print( course.getCourseID() );
      out.write("\r\n");
      out.write("                                            </span><br>\r\n");
      out.write("                                            <span style=\"font-weight: bold; display: inline-block;\">\r\n");
      out.write("                                                ");
      out.print( course.getCourseName() );
      out.write("\r\n");
      out.write("                                            </span>\r\n");
      out.write("                                        </button>\r\n");
      out.write("                                    </form>\r\n");
      out.write("                                    ");
 } 
      out.write("\r\n");
      out.write("                                        ");
} else {
      out.write("\r\n");
      out.write("                                            <p style=\"margin-top: 40px; font-weight: bold;\">No courses found</p>\r\n");
      out.write("                                            ");
 } 
      out.write("\r\n");
      out.write("                                ");
} else { 
      out.write("\r\n");
      out.write("                                    <p style=\"margin-top: 40px; font-weight: bold;\">Please enter a course code and click Search to find courses.</p>\r\n");
      out.write("                                    ");
 } 
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"container\">\r\n");
      out.write("                        <div style=\"width: 80%; max-width: 600px;text-align: left;\">\r\n");
      out.write("                            <h2>Current Enrolments</h2>\r\n");
      out.write("                            ");
 List<Course> currentEnrolments = (List<Course>)
                                    session.getAttribute("currentEnrolments");
                                    if(currentEnrolments!=null && !currentEnrolments.isEmpty()) { 
      out.write("\r\n");
      out.write("                                    <table\r\n");
      out.write("                                        style=\"width: 100%; border: 1px solid #c5c5c5;border-collapse: collapse; margin-top: 20px;\">\r\n");
      out.write("                                        <thead style=\"background-color: #c5c5c5;\">\r\n");
      out.write("                                            <tr>\r\n");
      out.write("                                                <th>CourseID</th>\r\n");
      out.write("                                                <th>Course Name</th>\r\n");
      out.write("                                                <th>Credits</th>\r\n");
      out.write("                                                <th></th>\r\n");
      out.write("                                            </tr>\r\n");
      out.write("                                        </thead>\r\n");
      out.write("                                        <tbody>\r\n");
      out.write("                                            ");
 for (Course course : currentEnrolments) { 
      out.write("\r\n");
      out.write("                                                <tr>\r\n");
      out.write("                                                    <td>\r\n");
      out.write("                                                        ");
      out.print(course.getCourseID() );
      out.write("\r\n");
      out.write("                                                    </td>\r\n");
      out.write("                                                    <td>\r\n");
      out.write("                                                        ");
      out.print(course.getCourseName() );
      out.write("\r\n");
      out.write("                                                    </td>\r\n");
      out.write("                                                    <td>\r\n");
      out.write("                                                        ");
      out.print(course.getCredits() );
      out.write("\r\n");
      out.write("                                                    </td>\r\n");
      out.write("                                                    <td style=\"text-align: center; width: 100px;\">\r\n");
      out.write("                                                        <form action=\"CourseEnrolmentServlet\" method=\"post\">\r\n");
      out.write("                                                            <input type=\"hidden\" name=\"action\" value=\"confirmDrop\" />\r\n");
      out.write("                                                            <input type=\"hidden\" name=\"courseID\"\r\n");
      out.write("                                                                value=\"");
      out.print( course.getCourseID() );
      out.write("\" />\r\n");
      out.write("                                                            <button type=\"submit\"\r\n");
      out.write("                                                                style=\"background-color: #c50000;\">\r\n");
      out.write("                                                                 &ndash;<span style=\"font-weight: bold;\">  Drop</span>\r\n");
      out.write("                                                            </button>\r\n");
      out.write("                                                        </form>\r\n");
      out.write("                                                    </td>\r\n");
      out.write("                                                </tr>\r\n");
      out.write("                                                ");
 } 
      out.write("\r\n");
      out.write("                                        </tbody>\r\n");
      out.write("                                    </table>\r\n");
      out.write("                                    ");
} else {
      out.write("\r\n");
      out.write("                                        <p style=\"margin-top: 40px; font-weight: bold;\">You are not enrolled in any\r\n");
      out.write("                                            courses this semester.</p>\r\n");
      out.write("                                        ");
 } 
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    ");
      out.write("\r\n");
      out.write("    <style>\r\n");
      out.write("        .sidebar {\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            width: 30%;\r\n");
      out.write("            min-width: 200px;\r\n");
      out.write("            max-width: 400px;\r\n");
      out.write("            position: fixed;\r\n");
      out.write("            top: 0px;\r\n");
      out.write("            border-left: 1px solid #c5c5c5;\r\n");
      out.write("            border-top: 1px solid #c5c5c5;\r\n");
      out.write("            padding-top: 20px;\r\n");
      out.write("            transition: 0.3s;\r\n");
      out.write("            margin-top: 74px;\r\n");
      out.write("            background-color: #F1F6FF;\r\n");
      out.write("            right: 0;\r\n");
      out.write("            transform: translateX(100%);\r\n");
      out.write("            transition: transform 0.3s ease;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("        function closeSidebar() {\r\n");
      out.write("            var sidebar = document.getElementById(\"Sidebar\");\r\n");
      out.write("            sidebar.style.transform = \"translateX(100%)\";\r\n");
      out.write("            sidebar.style.boxShadow = \"none\";\r\n");
      out.write("        }\r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("    <!-- show sidebar with open motion or not -->\r\n");
      out.write("    ");
 Boolean showSidebar=(Boolean) request.getAttribute("showSidebar"); Boolean openSidebarAnim=(Boolean)
        request.getAttribute("openSidebar"); if (showSidebar !=null && showSidebar) { if(openSidebarAnim !=null &&
        openSidebarAnim) { 
      out.write("\r\n");
      out.write("        <script>\r\n");
      out.write("            function openSidebar() {\r\n");
      out.write("                var sidebar = document.getElementById(\"Sidebar\");\r\n");
      out.write("                sidebar.style.transform = \"translateX(0)\";\r\n");
      out.write("                sidebar.style.boxShadow = \"-4px 0 20px rgba(0, 0, 0, 0.08)\";\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            window.onload = function () {\r\n");
      out.write("                openSidebar();\r\n");
      out.write("            };\r\n");
      out.write("        </script>\r\n");
      out.write("        ");
 } else {
      out.write("\r\n");
      out.write("            <style>\r\n");
      out.write("                .sidebar {\r\n");
      out.write("                    transform: translateX(0);\r\n");
      out.write("                    transition: none;\r\n");
      out.write("                    box-shadow: -4px 0 20px rgba(0, 0, 0, 0.08);\r\n");
      out.write("                }\r\n");
      out.write("            </style>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    ");
 Course targetCourse=(Course) session.getAttribute("targetCourse"); if (targetCourse!=null) { 
      out.write("\r\n");
      out.write("                        <div class=\"sidebar\" id=\"Sidebar\" style=\"padding: 20px\">\r\n");
      out.write("                            <div style=\"display: flex; justify-content: space-between;align-items: end;\">\r\n");
      out.write("                                <p style=\"margin-right: 20px;color:#003AA6; \">\r\n");
      out.write("                                    ");
      out.print( targetCourse.getCourseID() );
      out.write("\r\n");
      out.write("                                </p>\r\n");
      out.write("                                <button class=\"icon-container\"\r\n");
      out.write("                                    style=\"padding: 2px 2px;border-radius: 100px;background-color: #F1F6FF;\"\r\n");
      out.write("                                    onclick=\"closeSidebar()\">\r\n");
      out.write("                                    <img src=\"/images/X.png\" height=\"24px\" /></button>\r\n");
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <p style=\"font-weight: bold;\">\r\n");
      out.write("                                ");
      out.print( targetCourse.getCourseName() );
      out.write("\r\n");
      out.write("                            </p>\r\n");
      out.write("                            <p style=\"margin-bottom: 30px;font-size: 14px;\">\r\n");
      out.write("                                ");
      out.print( targetCourse.getCredits() );
      out.write(" Credits\r\n");
      out.write("                            </p>\r\n");
      out.write("\r\n");
      out.write("                            <p style=\"font-weight: bold; margin-bottom: 5px;\">Prerequisite <br><span\r\n");
      out.write("                                    style=\"font-size: 14px\">(must be\r\n");
      out.write("                                    completed)</span></p>\r\n");
      out.write("                            <p style=\"font-size: 14px;\">\r\n");
      out.write("                                ");
 List<String> PrerequisiteCourses = (List<String>)
                                        session.getAttribute("prerequisite");
                                        if (PrerequisiteCourses == null || PrerequisiteCourses.isEmpty()) {
                                        out.print("No prerequisite listed");
                                        } else {
                                        out.print(String.join(", ", PrerequisiteCourses));
                                        }
                                
      out.write("\r\n");
      out.write("                            </p>\r\n");
      out.write("                            <p style=\"font-weight: bold;margin-top: 30px; margin-bottom: 5px\">Assumed Knowledge</p>\r\n");
      out.write("                            <p style=\"font-size: 14px;\">\r\n");
      out.write("                                ");
 List<String> assumedKnowCourses = (List<String>)
                                        session.getAttribute("assumedknowledge");
                                        if (assumedKnowCourses == null || assumedKnowCourses.isEmpty()) {
                                        out.print("No assumed knowledge listed");
                                        } else {
                                        out.print(String.join(", ", assumedKnowCourses));
                                        }
                                
      out.write("\r\n");
      out.write("                            </p>\r\n");
      out.write("                            <div class=\"button-container\">\r\n");
      out.write("                                <form action=\"CourseEnrolmentServlet\" method=\"post\">\r\n");
      out.write("                                    <input type=\"hidden\" name=\"action\" value=\"confirm\" />\r\n");
      out.write("                                    <input type=\"hidden\" name=\"courseID\" value=\"");
      out.print( targetCourse.getCourseID());
      out.write("\" />\r\n");
      out.write("                                    <button type=\"submit\"\r\n");
      out.write("                                        style=\"padding: 6px 20px;font-size: 16px;margin-top: 40px;\">Enrol</button>\r\n");
      out.write("                                </form>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("                        ");
      out.write("\r\n");
      out.write("<!-- show modal if error exist -->\r\n");
 Boolean error=(Boolean) request.getAttribute("error"); 
      out.write("\r\n");
      out.write("    <dialog id=\"error\">\r\n");
      out.write("        <div style=\"display: flex;align-items: center;margin-bottom: 20px;\">\r\n");
      out.write("            <img src=\"../images/Alert circle.png\" height=\"20px\" />\r\n");
      out.write("            <h4 style=\"margin-left: 10px;\">\r\n");
      out.write("                ");
      out.print( request.getAttribute("errorTitle"));
      out.write("\r\n");
      out.write("            </h4>\r\n");
      out.write("        </div>\r\n");
      out.write("        <p style=\"margin-bottom: 20px\">\r\n");
      out.write("            ");
      out.print( request.getAttribute("errorContent"));
      out.write("\r\n");
      out.write("        </p>\r\n");
      out.write("        <div class=\"button-container\">\r\n");
      out.write("            <button commandfor=\"error\" command=\"close\" style=\"width: 60px;\">OK</button>\r\n");
      out.write("        </div>\r\n");
      out.write("    </dialog>\r\n");
      out.write("\r\n");
      out.write("    ");
 if (error !=null && error) {
      out.write("\r\n");
      out.write("        <script>\r\n");
      out.write("            const dialog = document.getElementById(\"error\");\r\n");
      out.write("            dialog.showModal();\r\n");
      out.write("        </script>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                            ");
      out.write("\r\n");
      out.write("<!-- show modal if warning exist -->\r\n");
 Boolean warning=(Boolean) request.getAttribute("warning"); 
      out.write("\r\n");
      out.write("    <dialog id=\"warning\">\r\n");
      out.write("        <div style=\"display: flex;align-items: center;margin-bottom: 20px;\">\r\n");
      out.write("            <img src=\"../images/Alert triangle.png\" height=\"20px\" />\r\n");
      out.write("            <h4 style=\"margin-left: 10px;\">\r\n");
      out.write("                ");
      out.print( request.getAttribute("warningTitle"));
      out.write("\r\n");
      out.write("            </h4>\r\n");
      out.write("        </div>\r\n");
      out.write("        <p style=\"margin-bottom: 20px\">\r\n");
      out.write("            ");
      out.print( request.getAttribute("warningContent"));
      out.write("\r\n");
      out.write("        </p>\r\n");
      out.write("        <div class=\"button-container\">\r\n");
      out.write("            <form action=\"CourseEnrolmentServlet\" method=\"post\">\r\n");
      out.write("                <input type=\"hidden\" name=\"action\" value=\"enrol\" />\r\n");
      out.write("                ");
 String warningCourseID =(String) request.getAttribute("course"); 
      out.write("\r\n");
      out.write("                <input type=\"hidden\" name=\"courseID\" value=\"");
      out.print( warningCourseID  );
      out.write("\" />\r\n");
      out.write("                <button>Proceed</button>\r\n");
      out.write("            </form>\r\n");
      out.write("            <button style=\"color: black;background-color: white;border: 1px solid #003AA6;\" commandfor=\"warning\" command=\"close\">\r\n");
      out.write("                Cancel\r\n");
      out.write("            </button>\r\n");
      out.write("        </div>\r\n");
      out.write("    </dialog>\r\n");
      out.write("\r\n");
      out.write("    ");
 if (warning !=null && warning) {
      out.write("\r\n");
      out.write("        <script>\r\n");
      out.write("            const dialog = document.getElementById(\"warning\");\r\n");
      out.write("            dialog.showModal();\r\n");
      out.write("        </script>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                ");
      out.write("<!-- show modal if confirming enrolment -->\r\n");
 Boolean confirm=(Boolean) request.getAttribute("confirm"); 
      out.write("\r\n");
      out.write("    <dialog id=\"confirm\">\r\n");
      out.write("        <div style=\"display: flex;align-items: center;margin-bottom: 20px;\">\r\n");
      out.write("            <h4>\r\n");
      out.write("                ");
      out.print( request.getAttribute("confirmTitle"));
      out.write("\r\n");
      out.write("            </h4>\r\n");
      out.write("        </div>\r\n");
      out.write("        <p style=\"margin-bottom: 20px\">\r\n");
      out.write("            ");
      out.print( request.getAttribute("confirmContent"));
      out.write("\r\n");
      out.write("        </p>\r\n");
      out.write("        <div class=\"button-container\">\r\n");
      out.write("            <form action=\"CourseEnrolmentServlet\" method=\"post\">\r\n");
      out.write("                ");
 String confirmAction = (String) request.getAttribute("confirmAction"); 
      out.write("\r\n");
      out.write("                <input type=\"hidden\" name=\"action\" value=\"");
      out.print( confirmAction );
      out.write("\" />\r\n");
      out.write("                ");
 String courseID =(String) request.getAttribute("course"); 
      out.write("\r\n");
      out.write("                <input type=\"hidden\" name=\"courseID\" value=\"");
      out.print( courseID  );
      out.write("\" />\r\n");
      out.write("                <button>Proceed</button>\r\n");
      out.write("            </form>\r\n");
      out.write("            <button style=\"color: black;background-color: white;border: 1px solid #003AA6;\" commandfor=\"confirm\"\r\n");
      out.write("                command=\"close\">Cancel</button>\r\n");
      out.write("        </div>\r\n");
      out.write("    </dialog>\r\n");
      out.write("\r\n");
      out.write("    ");
 if (confirm !=null && confirm) {
      out.write("\r\n");
      out.write("        <script>\r\n");
      out.write("            const dialog = document.getElementById(\"confirm\");\r\n");
      out.write("            dialog.showModal();\r\n");
      out.write("        </script>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("                </body>\r\n");
      out.write("\r\n");
      out.write("                </html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
