/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.5
 * Generated at: 2026-03-05 02:46:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import seng2050.Course;

public final class courseenrolment_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("seng2050.Course");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("    .sidebar {\r\n");
      out.write("        height: 100%;\r\n");
      out.write("        width: 30%;\r\n");
      out.write("        min-width: 200px;\r\n");
      out.write("        max-width: 400px;\r\n");
      out.write("        position: fixed;\r\n");
      out.write("        top: 0px;\r\n");
      out.write("        right: -250px;\r\n");
      out.write("        border-left: 1px solid #c5c5c5;\r\n");
      out.write("        border-top: 1px solid #c5c5c5;\r\n");
      out.write("        padding-top: 20px;\r\n");
      out.write("        transition: 0.3s;\r\n");
      out.write("        margin-top: 74px;\r\n");
      out.write("        background-color: #F1F6FF;\r\n");
      out.write("        box-shadow: -8px 0 20px rgba(0, 0, 0, 0.10);\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
 Course targetCourse=(Course) request.getAttribute("targetCourse"); if (targetCourse!=null)
    { 
      out.write("\r\n");
      out.write("    <div class=\"sidebar\" id=\"Sidebar\" style=\"padding: 20px\">\r\n");
      out.write("        <div style=\"display: flex; justify-content: space-between;align-items: end;\">\r\n");
      out.write("            <p style=\"margin-right: 20px;color:#003AA6; \">\r\n");
      out.write("                ");
      out.print( targetCourse.getCourseID() );
      out.write("\r\n");
      out.write("            </p>\r\n");
      out.write("            <button class=\"icon-container\" style=\"padding: 2px 2px;border-radius: 100px;background-color: #F1F6FF;\" onclick=\"location.href='FindCourseServlet'\">\r\n");
      out.write("                    <img src=\"/images/X.png\" height=\"24px\" /></button>\r\n");
      out.write("        \r\n");
      out.write("        </div>\r\n");
      out.write("        <p style=\"font-weight: bold;\">\r\n");
      out.write("            ");
      out.print( targetCourse.getCourseName() );
      out.write("\r\n");
      out.write("        </p>\r\n");
      out.write("        <p style=\"margin-bottom: 30px;font-size: 14px;\">");
      out.print( targetCourse.getCredits() );
      out.write(" Credits</p>\r\n");
      out.write("        \r\n");
      out.write("        <p style=\"font-weight: bold; margin-bottom: 5px;\">Prerequisite <br><span style=\"font-size: 14px\">(must be completed)</span></p>\r\n");
      out.write("        <p style=\"font-size: 14px;\">");
      out.print(request.getAttribute("prerequisite"));
      out.write("</p>\r\n");
      out.write("        <p style=\"font-weight: bold;margin-top: 30px; margin-bottom: 5px\">Assumed Knowledge</p>\r\n");
      out.write("        <p style=\"font-size: 14px;\">");
      out.print(request.getAttribute("assumedknowledge"));
      out.write("</p>\r\n");
      out.write("        <div class=\"button-container\">\r\n");
      out.write("            <form action=\"CourseEnrolmentServlet\" method=\"post\">\r\n");
      out.write("                <input type=\"hidden\" name=\"courseID\" value=\"");
      out.print( targetCourse.getCourseID());
      out.write("\"/>\r\n");
      out.write("                <button type=\"submit\" style=\"padding: 5px 15px;font-size: 16px;margin-top: 40px;\">Enrol</button>\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    ");
 } 
      out.write("\r\n");
      out.write("    \r\n");
      out.write("        ");
 Boolean openSidebar=(Boolean) request.getAttribute("openSidebar"); if(openSidebar !=null && openSidebar) { 
      out.write("\r\n");
      out.write("            <script>\r\n");
      out.write("                function toggleSidebar() {\r\n");
      out.write("                    var sidebar = document.getElementById(\"Sidebar\");\r\n");
      out.write("                    if (sidebar.style.right === \"0px\") {\r\n");
      out.write("                        sidebar.style.right = \"-250px\"; // Close\r\n");
      out.write("                    } else {\r\n");
      out.write("                        sidebar.style.right = \"0px\";    // Open\r\n");
      out.write("                    }\r\n");
      out.write("                }\r\n");
      out.write("                window.onload = function () {\r\n");
      out.write("                    setTimeout(toggleSidebar, 10);\r\n");
      out.write("                };\r\n");
      out.write("\r\n");
      out.write("            </script>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
